jtype: Flow
version: '1'
with:
  port: 51000
  protocol: http
executors:
  - name: clip_t
    uses:
      jtype: CLIPEncoder
      with:
        device: cuda    # [THAY ĐỔI] Chuyển từ 'cpu' sang 'cuda'
        # model_name: openai/clip-vit-base-patch32 # (Tùy chọn) Có thể chỉ định model ở đây nếu cần
      metas:
        py_modules:
          - clip_server.executors.clip_torch